"""add category column to purpose table

Revision ID: 20a17f4cf1b0
Revises: 6cf65c4e75c6
Create Date: 2025-11-07 20:37:56.960236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20a17f4cf1b0'
down_revision = '6cf65c4e75c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purposes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('caegory', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purposes', schema=None) as batch_op:
        batch_op.drop_column('caegory')

    # ### end Alembic commands ###
