"""Refactor items table: remove auto_gen column and add basic condition columns (e.g. for_gender, for_season, for_purpose)

Revision ID: 310c19346fb0
Revises: 9a6d05573416
Create Date: 2025-11-03 12:03:01.992235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '310c19346fb0'
down_revision = '9a6d05573416'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('for_gender', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('for_season', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('for_weather', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('for_transport', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('min_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_days', sa.Integer(), nullable=True))
        batch_op.drop_column('auto_gen')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auto_gen', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('max_days')
        batch_op.drop_column('min_days')
        batch_op.drop_column('for_transport')
        batch_op.drop_column('for_weather')
        batch_op.drop_column('for_season')
        batch_op.drop_column('for_gender')

    # ### end Alembic commands ###
