"""Add weather_data and weather_last_update to Travel

Revision ID: 32fc6dfa7d91
Revises: 9a1b8cdf6344
Create Date: 2025-12-02 16:05:10.331105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32fc6dfa7d91'
down_revision = '9a1b8cdf6344'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('travels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weather_data', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('weather_last_update', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('travels', schema=None) as batch_op:
        batch_op.drop_column('weather_last_update')
        batch_op.drop_column('weather_data')

    # ### end Alembic commands ###
