"""Allow NULL for auto_gen column in Item table

Revision ID: 34da2a920fdf
Revises: 709ed13967e1
Create Date: 2025-09-09 21:56:48.289700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34da2a920fdf'
down_revision = '709ed13967e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('auto_gen',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('my_set_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_mysetitems_custom_item'), postgresql_where='(custom_item_id IS NOT NULL)')
        batch_op.drop_index(batch_op.f('uq_mysetitems_item'), postgresql_where='(item_id IS NOT NULL)')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('my_set_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_mysetitems_item'), ['my_set_id', 'item_id'], unique=True, postgresql_where='(item_id IS NOT NULL)')
        batch_op.create_index(batch_op.f('uq_mysetitems_custom_item'), ['my_set_id', 'custom_item_id'], unique=True, postgresql_where='(custom_item_id IS NOT NULL)')

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('auto_gen',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###
