"""add_transport_column_to_travels

Revision ID: 3ce0688482ad
Revises: 9b5ef7537150
Create Date: 2025-10-02 19:54:24.326170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ce0688482ad'
down_revision = '9b5ef7537150'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('travels', sa.Column('transport', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('travels', 'transport')
    # ### end Alembic commands ###
