"""add_transport_column_to_travels

Revision ID: 3ce0688482ad
Revises: 9b5ef7537150
Create Date: 2025-10-02 19:54:24.326170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ce0688482ad'
down_revision = '9b5ef7537150'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('auto_gen', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('bags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('length_cm', sa.Float(), nullable=False),
    sa.Column('width_cm', sa.Float(), nullable=False),
    sa.Column('height_cm', sa.Float(), nullable=False),
    sa.Column('volume_l', sa.Float(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('custom_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('size_length_cm', sa.Float(), nullable=True),
    sa.Column('size_width_cm', sa.Float(), nullable=True),
    sa.Column('size_height_cm', sa.Float(), nullable=True),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('my_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('travels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('destination', sa.String(), nullable=False),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=False),
    sa.Column('male_count', sa.Integer(), nullable=True),
    sa.Column('female_count', sa.Integer(), nullable=True),
    sa.Column('child_count', sa.Integer(), nullable=True),
    sa.Column('purpose', sa.String(), nullable=False),
    sa.Column('transport', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('my_set_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('my_set_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('custom_item_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['custom_item_id'], ['custom_items.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['my_set_id'], ['my_sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('packing_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bag_id', sa.Integer(), nullable=False),
    sa.Column('travel_id', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.String(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['bag_id'], ['bags.id'], ),
    sa.ForeignKeyConstraint(['travel_id'], ['travels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('travel_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('my_set_item_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('custom_item_id', sa.Integer(), nullable=True),
    sa.Column('travel_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('check_flag', sa.Boolean(), nullable=False),
    sa.CheckConstraint('(item_id IS NOT NULL OR custom_item_id IS NOT NULL OR my_set_item_id IS NOT NULL)', name='check_travelitems_not_all_null'),
    sa.ForeignKeyConstraint(['custom_item_id'], ['custom_items.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['my_set_item_id'], ['my_set_items.id'], ),
    sa.ForeignKeyConstraint(['travel_id'], ['travels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('travel_items')
    op.drop_table('packing_plans')
    op.drop_table('my_set_items')
    op.drop_table('travels')
    op.drop_table('my_sets')
    op.drop_table('custom_items')
    op.drop_table('bags')
    op.drop_table('users')
    op.drop_table('items')
    # ### end Alembic commands ###
