"""Add PurposeItem table; add cascade on Purpose.travel_purposes relationship (ORM only)

Revision ID: 6bd041aa98a6
Revises: d64b82a4faad
Create Date: 2025-11-10 19:54:37.498185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bd041aa98a6'
down_revision = 'd64b82a4faad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purpose_items',
    sa.Column('purpose_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['purpose_id'], ['purposes.id'], ),
    sa.PrimaryKeyConstraint('purpose_id', 'item_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purpose_items')
    # ### end Alembic commands ###
