"""Add Purpose and TravelPurpose tables

Revision ID: 6cf65c4e75c6
Revises: 310c19346fb0
Create Date: 2025-11-05 22:20:51.198147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cf65c4e75c6'
down_revision = '310c19346fb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purposes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('travel_purposes',
    sa.Column('travel_id', sa.Integer(), nullable=False),
    sa.Column('purpose_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['purpose_id'], ['purposes.id'], ),
    sa.ForeignKeyConstraint(['travel_id'], ['travels.id'], ),
    sa.PrimaryKeyConstraint('travel_id', 'purpose_id')
    )
    with op.batch_alter_table('travels', schema=None) as batch_op:
        batch_op.drop_column('purpose')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('travels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purpose', sa.VARCHAR(), autoincrement=False, nullable=False))

    op.drop_table('travel_purposes')
    op.drop_table('purposes')
    # ### end Alembic commands ###
