"""update transport and item fields

Revision ID: 7ad8226790e6
Revises: 9640090e0153
Create Date: 2025-12-07 16:42:42.058873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ad8226790e6'
down_revision = '9640090e0153'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_general', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('fixed_quantity', sa.Integer(), nullable=True))
        batch_op.alter_column('for_transport',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=False,
               postgresql_using="for_transport::json"
               )

    with op.batch_alter_table('travels', schema=None) as batch_op:
        batch_op.alter_column('transport',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True,
               postgresql_using="transport::json"
               )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('travels', schema=None) as batch_op:
        batch_op.alter_column('transport',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('for_transport',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
        batch_op.drop_column('fixed_quantity')
        batch_op.drop_column('is_general')

    # ### end Alembic commands ###
