"""drop quantity from MySetItem

Revision ID: 9a1b8cdf6344
Revises: 6bd041aa98a6
Create Date: 2025-11-20 18:16:30.870365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a1b8cdf6344'
down_revision = '6bd041aa98a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('my_set_items', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('my_set_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
