"""Add auto_added to TravelItem

Revision ID: cb1179585874
Revises: 7ad8226790e6
Create Date: 2025-12-07 22:25:31.569259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb1179585874'
down_revision = '7ad8226790e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('travel_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auto_added', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('travel_items', schema=None) as batch_op:
        batch_op.drop_column('auto_added')

    # ### end Alembic commands ###
