"""Fix typo: caegory -> category

Revision ID: d64b82a4faad
Revises: 20a17f4cf1b0
Create Date: 2025-11-08 00:25:39.739394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd64b82a4faad'
down_revision = '20a17f4cf1b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purposes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(), nullable=False))
        batch_op.drop_column('caegory')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purposes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('caegory', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('category')

    # ### end Alembic commands ###
